Repository Netzerone/cheatjudge-fe, pull requests merged in 2025-03, with the labels that each got.

#4 레이아웃 기본 설정
  public/duke.png
  public/oia-cat.png
  src/App.tsx
Labels: feature

#7 외부 설계 적용 - 학생용
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/ui/badge.tsx
  src/components/ui/card.tsx
  src/components/ui/select.tsx
  src/components/ui/tabs.tsx
  src/components/ui/tooltip.tsx
  src/pages/IDE.tsx
  src/pages/Lobby.tsx
  src/routes.tsx
Labels: feature, style

#8 프로젝트 기본 라우팅 설정
  src/App.tsx
  src/components/common/.gitkeep
  src/components/domain/.gitkeep
  src/components/layout/AdminLayout.tsx
  src/components/layout/UserLayout.tsx
  src/contexts/QueryProvider.tsx
  src/pages/Landing/index.tsx
  src/pages/User/Exam.tsx
  src/pages/User/UserDashboard.tsx
  src/routes.tsx
Labels: refactor
